### PR TITLE
Create basic eslint and prettier config

### PR DESCRIPTION
**Pull request by Oricul**
This is a basic setup for eslint and prettier. For VSC, you should have eslint and prettier installed. Using npm, it's just `npm install` while in the project directory.

### CODE REVIEW

**Comment by Oricul** [comment]
P.S., I spent way too much time on this.

**Comment by Oricul** [comment]
Once this is merged, I'll grab another branch to resolve linting issues, then return to working on https://github.com/aclist/kbin-kes/pull/109

**Comment by aclist** [comment]
> P.S., I spent way too much time on this.

I hope you didn't do this solely on my behalf. Clarification follows...

> This is a basic setup for eslint and prettier. For VSC, you should have eslint and prettier installed. Using npm, it's just npm install while in the project directory.

Oh, I should clarify, I use vim, ALE, and a variety of language servers and REPLs. I have eslint installed as a system package and I'm using nvm to set a virtual environment because the whole node ecosystem is so bloated and causes sheer hell on a rolling release distribution if you don't isolate this stuff from system packages. That `sane.sh` you see is a build environment sanity script I just wrote to ensure that, among other things, the nvm prefix is set up, eslint is loaded, and everything is good to go.

I have autolinting, autofixing, and warnings enabled now just using ALE. ALE implements a more generalized language server client protocol. As far as I can tell, Prettier does the same thing as ALE and isn't nearly as well supported when it comes to vim plugins. Personally, I don't want to pull in a bunch of node packages unnecessarily since we aren't building a web site or anything here, but everyone has a different development environment.

*All that being said* :eyes: , insofar as this is a project written in JS and other people may wish to adhere to the same standards, and having these files kicking around doesn't hurt anybody, much less me, I'm fine with inclusion. Although I was thinking it'd be more of a codified written standard that contributors can adhere to however they see fit. I.e., I think it's good to write these things down, too.

I'll update precommit hooks to run `npm version major|minor|version|prelease` accordingly so that the file is updated.

> Once this is merged, I'll grab another branch to resolve linting issues, then return to working on https://github.com/aclist/kbin-kes/pull/109

I think I beat you to it an hour and a half ago or so. I normalized all of the files to four spaces and ran everything through ESLint and fixed all of the errors/warnings through a mix of manual and autofixing. I think there are still a handful of warnings kicking around in your two big mods, mainly around unused variables or something unimportant.

It also found a fair amount of stale code and security aspects like `Unexpected lexical declaration in case block`, so cleaned all of that, too, and it's looking pretty darn good. I regret dragging my heels on this and not doing sooner, thanks for the kick in the pants. Onward and upward!

P.D. Also set up the initial branch merge rules discussed in https://github.com/aclist/kbin-kes/issues/121

It should be a lot harder to inadvertently shoot ourselves in the foot now.

**Comment by Oricul** [comment]
> I hope you didn't do this solely on my behalf.

Nah, it's good for me to learn it and it'll be good to enforce these across the board.

> > Once this is merged, I'll grab another branch to resolve linting issues, then return to working on #109
> 
> I think I beat you to it an hour and a half ago or so. I normalized all of the files to four spaces and ran everything through ESLint and fixed all of the errors/warnings through a mix of manual and autofixing.

I saw the normalization commit, but doesn't hurt to double check.

**Comment by aclist** [comment]
> I saw the normalization commit, but doesn't hurt to double check.

Agreed!

**Pull request merged**
