### PR TITLE
Feature: Multiple author support

### PR DESCRIPTION
**Pull request by Oricul**
While implementing multi-author support (in an array), I changed some nearby items. I broke HTML strings into their JS counterparts to be more readable. I also made author links link to the current instance instead of kbin.social always.

### CODE REVIEW

**Comment by Oricul** [comment]
This PR is to implement https://github.com/aclist/kbin-kes/issues/66 .

**Comment by aclist** [comment]
Very nice, the logic to add elements was unspeakably convoluted and getting unreadable. I keep thinking there is more room to abstract here somewhere by creating smaller functions that construct the elements in a less imperative manner, but it doesn't seem important for now because the UI is mostly fixed now. It would make future changes easier, though

**Comment by aclist** [comment]
Would you mind resubmitting this against `testing` now that the safeGM patch is merged in? I thought I resolved the merge conflict, but ended up killing some chunk of code in the process, so had to revert it. Sorry.

**Comment by Oricul** [comment]
> Would you mind resubmitting this against `testing` now that the safeGM patch is merged in? I thought I resolved the merge conflict, but ended up killing some chunk of code in the process, so had to revert it. Sorry.

Unfortunately I can't.
0 changed files

**Comment by aclist** [comment]
> Can you revert the change in this PR?

Unfortunately I cannot, the content is already stale. If you have a local version of the multi author code that differs from the current state of testing, create a new branch and PR?

**Pull request merged**
