### PR TITLE
Adds safeGM function for generic support of *monkey variants (#74)

### PR DESCRIPTION
**Pull request by aclist**
See commit notes for details.

Needs testing on combinations of:

- Firefox
- Chromium
- Other

- GreaseMonkey
- TamperMonkey
- ViolentMonkey
- Userscripts

Main affected problem surface based on reports is:
- Firefox + GreaseMonkey
- Safari + Userscripts

### CODE REVIEW

**Comment by aclist** [comment]
Note that I didn't update any of the mods themselves to call safeGM, just modified the main script.

This test below is working for me (Firefox/TamperMonkey) as a minimum reproducible example.

Even so it may generally be a good idea to host safeGM in its own script for maintainability purposes, and because it could be useful as its own helper function.

```
// ==UserScript==
// @name          KES
// @namespace     https://github.com/aclist/
// @license       MIT
// @version       2.0.2
// @description   Kbin Enhancement Suite
// @author        aclist
// @match         https://kbin.social/*
// @match         https://lab2.kbin.pub/*
// @match         https://lab3.kbin.pub/*
// @match         https://fedia.io/*
// @match         https://karab.in/*
// @grant         GM_addStyle
// @grant         GM_getResourceText
// @grant         GM_xmlhttpRequest
// @grant         GM_info
// @grant         GM_getValue
// @grant         GM_setValue
// @grant         GM_getResourceText
// @grant         GM_setClipboard
// @grant         GM.addStyle
// @grant         GM.getResourceText
// @grant         GM.xmlHttpRequest
// @grant         GM.info
// @grant         GM.getValue
// @grant         GM.setValue
// @grant         GM.getResourceText
// @grant         GM.setClipboard
// @connect       raw.githubusercontent.com
// @connect       github.com
// @icon          https://kbin.social/favicon.svg
// @require       http://code.jquery.com/jquery-3.4.1.min.js
// @require       https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.7.0/highlight.min.js
// @require https://gist.githubusercontent.com/aclist/0d5e4547ed5ad45f4acb915e4ae612d5/raw/ca5a6be6ed05d933ecee64413a1adc1fc1393edd/d.js
// @resource      kes_css https://github.com/aclist/kbin-kes/raw/testing/kes.css
// @resource      kes_layout https://github.com/aclist/kbin-kes/raw/testing/ui.json
// @downloadURL    https://github.com/aclist/kbin-scripts/raw/testing/kes.user.js
// @updateURL      https://github.com/aclist/kbin-scripts/raw/testing/kes.user.js
// ==/UserScript==
let gmPrefix
try {
	if(GM_info){
		gmPrefix = "GM_"
	} else {
		gmPrefix = "GM."
	}
} catch {
	console.log(error);
}
    console.log("GM prefix is " + gmPrefix);
    window.safeGM = function(func,...args){
        let use
        let underscore = {
            setValue(...args) { return GM_setValue(...args) },
            getValue(...args) { return GM_getValue(...args) },
            addStyle(...args) { return GM_addStyle(...args)},
            xmlhttpRequest(...args) { return GM_xmlhttpRequest(...args)},
            setClipboard(...args) { return GM_setClipboard(...args)},
            getResourceText(...args) { return GM_getResourceText(...args)},
            info() { return GM_info }
        }
        let dot = {
            setValue(...args) { return GM.setValue(...args) },
            getValue(...args) { return GM.getValue(...args) },
            addStyle(...args) { return GM.addStyle(...args)},
            xmlhttpRequest(...args) { return GM.xmlHttpRequest(...args)},
            setClipboard(...args) { return GM.setClipboard(...args)},
            getResourceText(...args) { return GM.getResourceText(...args)},
            info() { return GM_info }
        }
        if (gmPrefix === "GM_") {
            use = underscore
        } else {
            use = dot
        }
        return use[func](...args);
    }

//object used for interpolation of function names
const funcObj = {
    bu: bu
};

//calling test "mod" with the entrypoint "bu"
//mod sets the named value "foo" to the string "bar"
funcObj["bu"]();
let BU = safeGM("getValue","foo");
console.log(BU)
```

**Comment by Oricul** [comment]
> Note that I didn't update any of the mods themselves to call safeGM, just modified the main script.
> 
> This test below is working for me (Firefox/TamperMonkey) as a minimum reproducible example.
I can confirm the change itself works in the main script, but that's why I tested a change in a mod where I discovered it was undefined. 

>Even so it may generally be a good idea to host safeGM in its own script for maintainability purposes, and because it could be useful as its own helper function.
Agreed! https://github.com/aclist/kbin-kes/pull/82 should handle this.

**Comment by aclist** [comment]
I see, just so I understand better, can you point to the mod and the method of invocation? There is still refactoring to be done here, so would like to know the implications. Regardless, I think sourcing the whole script first is nice because it keeps this logic outside of the main script and cleans things up quite a bit.

**Comment by artillect** [comment]
Here's the [Userscripts](https://github.com/quoid/userscripts#api) API docs, it uses GM. for everything, but also supports GM_ for xmlhttprequest and info

**Comment by Oricul** [comment]
> I see, just so I understand better, can you point to the mod and the method of invocation? There is still refactoring to be done here, so would like to know the implications. Regardless, I think sourcing the whole script first is nice because it keeps this logic outside of the main script and cleans things up quite a bit.

The mod I tested with was **code-highlighting.user.js**, and simply changed the following on line 1...
`javascript
//GM_addStyle(`
safeGM('addStyle', `
    .collapsed {
        display: none !important;
    }
`);
`

Then I tested to make sure collapsing was still working.

**Comment by aclist** [comment]
Initial outcome is that everything seems to load! But collapsible comments is going bananas, not loading its CSS correctly

**Comment by aclist** [comment]
Moving discussion over to #74

**Pull request merged**
