### PR TITLE
Change Font Size Mod

### PR DESCRIPTION
**Pull request by minnieoo**
This is a customizable mod that allows the user to change the font size of posts, comments, or both simultaneously. 

https://github.com/aclist/kbin-kes/assets/137783738/a436c923-e398-4a6f-9bde-f1bca4b09c7e

### CODE REVIEW

**Comment by aclist** [comment]
Take a look at this: https://github.com/aclist/kbin-kes/issues/72

I think it makes sense to incorporate as many elements as possible here, such as headers, posts, names, comments, description.

I would also take a look at the number input type: https://developer.mozilla.org/en/docs/Web/HTML/Element/input/number and map it to a point size increment.

This gives the user very granular control over their preferred point size and you don't have to set predefined sizes ahead of time, plus you can arrow up/down and increment/decrement on the fly. Maybe start it at a default size between 12pt or whatever is the equivalent to the default size in rem

**Comment by minnieoo** [comment]
o i missed that discussion, thanks for letting me know. ill try to apply this 👍🏽

**Comment by minnieoo** [comment]
@aclist maybe im wrong but is there no way to add steps for the number input within the manifest? for now i was just gonna add them using the dom but i thought maybe this would be good to have available. i didnt see anything for it in kes.user.js

**Comment by aclist** [comment]
We didn't implement steps, now that you mention it :crying_cat_face: 

Nor min/max... Number input seems like one of the more common ones to be used, so we should definitely extend this

**Comment by aclist** [comment]
I am adding this now, should be quick to do.

**Comment by aclist** [comment]
Added in 2.0.0-rc.25, just tested the helpbox and increments appearing in localstorage, didn't test it end to end, but should be good to go

**Pull request closed without merging**
