### PR TITLE
Fix Raw URLs

### PR DESCRIPTION
**Pull request by Pamasich**
As discussed in #205, this commit switches the `/raw/` urls to use `raw.githubusercontent.com` instead. That should fix the problem seen in that issue.

To keep things uniform, I've switched over all the /raw/ urls in the project, not just the ones in kes.user.js.

### CODE REVIEW

**Comment by Pamasich** [comment]
@aclist I just noticed while reading the [greasyfork issue](https://github.com/aclist/kbin-kes/issues/132) that you said

> If we reverted to using the github.com TLD instead of raw.githubusercontent.com, this should theoretically work. However, we switched to the second one because the first one is just performing a redirect, so wanted to save a few cycles there. Also, this feels slightly less robust than using the integrity hashes.

Am I interpreting this correctly that KES used to use raw.githubusercontent.com but then switched to /raw/ urls for some reason? Was that just greasyfork, or was there a different reason? Don't want to do a regression here.

**Comment by aclist** [comment]
If memory serves, we flip-flopped back and forth between them a few times because something about the interaction between *monkey's caching and GitHub's deferred caching mechanism was causing some users to see stale versions of files even when an update was pending for KES. I think we reverted to just letting GitHub handle the redirections because it should (?) fetch the more recent file after doing so. 

It still seems like the raw URL should be more consistent and avoid the CSS failing to load, but we should probably test whether an updated KES version triggers the monkey to fetch the new mod versions. It is relatively easy to revert.

Unfortunately, GitHub's caching mechanism is not well documented, so I can't say definitively what is going on.

I belive the @requires will never auto-update on monkey's side (falling back to the locally-stored resources) unless:

1. The entire script is reinstalled
2. The @requires in the updated script are no longer identical to the string literals in the previous version (e.g., if the remote URL to the mod includes a bumped version number or something)
3. The script pulls in a completely new @requires (new mod)

I think the second point could be an issue for us because mod names (and consequently, the URLs) never change. But as of this writing, "updating KES" essentially requires clicking the button and reinstalling the script, so I think point 1 is being satisfied. So...I don't think any of this should be a problem, it's just that we have to satisfy the twin objectives of fixing the CSS bug while also enabling the different monkey flavors to handle updating correctly.

**Comment by Pamasich** [comment]
I see, we'll have to see how this goes then.

> I belive the @requires will never auto-update on monkey's side (falling back to the locally-stored resources) unless:

Tampermonkey does allow the user to specify the @requires should be updated in regular intervals or even every time the userscript gets executed, but that seems to be a general setting for all userscripts. Not sure if the same functionality also exists on a per-userscript level and in other monkeys.

**Comment by aclist** [comment]
> I see, we'll have to see how this goes then.
> 
> > I belive the `@requires` will never auto-update on monkey's side (falling back to the locally-stored resources) unless:
> 
> Tampermonkey does allow the user to specify the `@requires` should be updated in regular intervals or even every time the userscript gets executed, but that seems to be a general setting for all userscripts. Not sure if the same functionality also exists on a per-userscript level and in other monkeys.

I don't think we've ever tried to atomically update a single mod over-the-air on the stable branch, so it shouldn't be an issue. I remember a lot of issues at the beginning due to people's different usage environments and monkey implementations. E.g., Mac with legacy GreaseMonkey, Windows with ViolentMonkey, and other esoteric combinations. I believe this is why we decided to make updating KES be a monolithic overhaul step, and to the extent possible try to discourage users from using upgrade buttons internal to their chosen extension.

By the way, when using words prefixed with the `@` symbol (e.g. `requires`), it will inadvertently ping a user on GitHub who has that name (I've made this mistake before and did so above), so it's best to wrap them in a code block so that they don't trigger, otherwise it will mention the user. I've edited the comments above to sanitize them.

**Comment by Pamasich** [comment]
> By the way, when using words prefixed with the `@` symbol (e.g. `requires`), it will inadvertently ping a user on GitHub who has that name (I've made this mistake before and did so above), so it's best to wrap them in a code block so that they don't trigger, otherwise it will mention the user. I've edited the comments above to sanitize them.

Oh, thanks for the explanation. Didn't know that, but it makes sense.

**Comment by Pamasich** [comment]
It seems like several urls are actually wrong here, I'll make a fix for that in a bit.

**Pull request merged**
