### PR TITLE
[MOD] Notifications panel with async

### PR DESCRIPTION
**Pull request by honkaiimpact3rd**
Here's how it should look like right now
image

Because of Kbin's styling using `!important` (which I explained in #133) it doesn't work properly
image

Removing it from `padding` and `display` fixes it
image
image

### CODE REVIEW

**Comment by aclist** [comment]
I've updated it to check the number of pages and handle these cases:

1. Only one page of notifications => draw no arrows
2. More than one page of notifications => draw forward arrow
3. If current page != 1  => draw back arrow
4. If no notifications => print generic "No new notifications!" message

Number 4 is styled with the selector `.noti-no-messages`. I didn't add any alignment or anything to it, so you'll have to choose where to display this or whether to center it in the panel.

I haven't added fetching the pages and reloading the content yet, but this should get the basic interface in place.

**Comment by honkaiimpact3rd** [comment]
Here's what I did in for notification context, right now it only shows snippets of messages but not if it's a message, reply, or new comment so it's a bit messy

Option 1 - Icons
image

Option 2 - Text
image

Option 3 - Icons with text
image

Not shown on screenshots, but with option 2&3 we would make the panel wider so it handles long usernames better

**Comment by aclist** [comment]
The text "mentioned you..." seems a bit verbose, I know that's the kbin default, but can we improve on that? Option 1 looks pretty good and highly readable if we can get it all aligned properly.

Hmm, I guess of the panel should definitely expand to fit arbitrary text dimensions, not sure. You would know better than me the implications of this.

Looks like the noti-header is not filling the whole frame, either.

**Comment by aclist** [comment]
What about putting the icon next to the message body? Would that make more sense, since it denotes the type of message, whereas the sender name is just its own thing?

Also, what about an arrow pointing down and to the right, i.e., inward towards the message snippet? The arrow pointing out and to the left kind of looks like it's a "reply out" ( == reply back) versus "incoming reply".

**Comment by honkaiimpact3rd** [comment]
>Looks like the noti-header is not filling the whole frame, either

noti-header is filling, but it looks like it's not because of the scrollbar, right now it's siblings with notifications so you would need to put all notifications together like this and make that scrollable instead of the entire panel

image
image

>what about an arrow pointing down and to the right, i.e., inward towards the message snippet? The arrow pointing out and to the left kind of looks like it's a "reply out" ( == reply back) versus "incoming reply".

I couldn't find an icon that would work for that that so what if the icon was just flipped? Akkoma (if you don't know what it is, it's a fedi microblogging platform like Mastodon) uses exactly this.

> What about putting the icon next to the message body? Would that make more sense, since it denotes the type of message, whereas the sender name is just its own thing?

Something like this? I guess it could work, but the circle design could be changed a bit

image

**Comment by aclist** [comment]
> noti-header is filling, but it looks like it's not because of the scrollbar, right now it's siblings with notifications so you would need to put all notifications together like this and make that scrollable instead of the entire panel

Makes sense, noted

> I couldn't find an icon in font awesome that would work for that that so what if the icon was just flipped? Akkoma (if you don't know what it is, it's a fedi microblogging platform like Mastodon) uses exactly this.

Seems reasonable to me 

> Something like this? I guess it could work, but the circle design could be changed a bit

Seems good, maybe the circle is not needed?

**Comment by aclist** [comment]
I hooked up the forward/back buttons to query the right page and load in the content. I think this just leaves the read/purge actions. I'll also take a look at rearranging the div structure later so that the scrollbar is below the header. I added something called `noti-panel-holder` which holds everything inside the panel, letting us remove this holder when loading in new pages and repopulate it.

**Comment by aclist** [comment]
Alright, I think I added everything that was missing and reworked a few things so that animations are always smooth when changing pages, reading/purging content, etc. Also added the API calls for reading and purging, and various error handling for if there are no unread messages, and fixed some click event bugs so that the panel doesn't try to reload itself when clicked. 

This should be everything functionality-wise, besides the message type icons and any remaining styling.

**Pull request merged**
